browserify:
	./node_modules/browserify/bin/cmd.js -o ./browserify_output.js ./browserify_module.js

browserify-emitter:
	./node_modules/browserify/bin/cmd.js -o ./browserify_emitter_output.js ./browserify_emitter_module.js
