test:
	./node_modules/mocha/bin/mocha *.test.js

karma:
	./node_modules/karma/bin/karma start

karma-sauce:
	./node_modules/karma/bin/karma start karma-sauce.conf.js

karma-ng-scenario:
	./node_modules/karma/bin/karma start karma-ng-scenario.conf.js

karma-ng-scenario-sauce:
	./node_modules/karma/bin/karma start karma-ng-scenario-sauce.conf.js

protractor:
	./node_modules/protractor/bin/protractor protractor_conf.js

protractor-angularjs.org:
	./node_modules/protractor/bin/protractor angularjs.org_protractor.conf.js 
